---
#Playbook to modify Local Admin Account on IOS devices
- name: F5 Virtual Server Configuration
  hosts: all
  connection: local
  gather_facts: false
  tasks:

  - name: Collect BIG-IP TCP MONITORS
    bigip_device_facts:  
      gather_subset:
        - tcp-monitors
      provider:
        server: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        user: "{{ lookup('env','F5_USERNAME') }}"
        password: "{{ lookup('env','F5_PASSWORD') }}"
        validate_certs: no
    delegate_to: localhost
    register: results
    when: tcp_monitor_select == 'ENABLED'

  - name: Retrieve existing TCP Monitors
    set_fact: 
      tcp_existing_monitors: "{{ results['tcp_monitors']| map(attribute='name')| list  }}"
    when: tcp_monitor_select == 'ENABLED'

  - name: Create TCP Monitor
    bigip_monitor_tcp:
      state: present
      name: "{{ 'tcp_monitor_' + tcp_monitor_port|string }}"
      ip: '*'
      port: "{{ tcp_monitor_port|string }}"
      provider:
        server: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        user: "{{ lookup('env','F5_USERNAME') }}"
        password: "{{ lookup('env','F5_PASSWORD') }}"
        validate_certs: no
    delegate_to: localhost    
    when: tcp_monitor_select == 'ENABLED'
      
  - name: Create HTTP Monitor
    bigip_monitor_http:
      state: present
      name: "{{ vs_name + '_http_monitor' }}"
      ip: '*'
      port: "{{ http_monitor_port|string }}"
      send: "{{ http_monitor_send  }}"
      receive: "{{ http_monitor_receive }}"
      provider:
        server: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        user: "{{ lookup('env','F5_USERNAME') }}"
        password: "{{ lookup('env','F5_PASSWORD') }}"
        validate_certs: no
    delegate_to: localhost
    register: http_monitor
    when:  http_monitor_select == 'ENABLED'

  - name: Create HTTPS Monitor
    bigip_monitor_https:
      state: present
      name: "{{ vs_name + '_https_monitor' }}"
      ip: '*'
      port: "{{ https_monitor_port|string }}"
      send: "{{ https_monitor_send  }}"
      receive: "{{ https_monitor_receive }}"
      provider:
        server: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        user: "{{ lookup('env','F5_USERNAME') }}"
        password: "{{ lookup('env','F5_PASSWORD') }}"
        validate_certs: no
    delegate_to: localhost
    register: http_monitor
    when: https_monitor_select == 'ENABLED'

  - name: Create persistence profile based on source IP
    bigip_profile_persistence_src_addr:
      name: "{{ vs_name + '_persist_profile_src_ip' }}"
      state: present
      match_across_services: yes 
      match_across_virtuals: yes
      #mirror: yes
      #mask: 255.255.255.255
      provider:
        server: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        user: "{{ lookup('env','F5_USERNAME') }}"
        password: "{{ lookup('env','F5_PASSWORD') }}"
        validate_certs: no
    delegate_to: localhost
    register: persistence_profile
    when: persistence_profile_src_addr == 'ENABLED'

  - name: Create a persistence cookie profile
    bigip_profile_persistence_cookie:
      name: "{{ vs_name + '_persist_profile_cookie' }}"
      cookie_name: "{{ vs_name + '_cookie' }}"
      provider:
        server: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        user: "{{ lookup('env','F5_USERNAME') }}"
        password: "{{ lookup('env','F5_PASSWORD') }}"
        validate_certs: no
    delegate_to: localhost    
    register: pesistence_profile
    when: persistence_profile_cookie =='ENABLED'

  - name: set-up persistence profile name
    set_fact:
      persistence_profile_name: |
            {%- if persistence_profile_src_addr == 'ENABLED' -%}
            {%- set profile_name = vs_name + '_persist_profile_src_ip' -%}
            {%- elif persistence_profile_cookie == 'ENABLED' -%}
            {%- set profile_name = vs_name + '_persist_profile_cookie' -%}
            {%- else -%}
            {%- set profile_name = '' -%}
            {%- endif -%}
            {{ profile_name }}
  - debug:
      msg: "{{ persistence_profile_name.split('\n')[0] }}"

  - name: Set list of Monitor for Pool
    set_fact:
      monitors_list: "{{  'dummy' | 
        monitors_list(tcp_monitor_select, tcp_monitor_port, http_monitor_select, https_monitor_select, vs_name) }}"

  - name: Create dedicated Pool for the Virtual Server
    bigip_pool:
      state: present
      name: "{{ vs_name + '_pool'  }}"
      partition: Common
      monitor_type: and_list
      lb_method: "{{ lb_algorithm  }}"
      monitors: "{{ monitors_list  }}"
      provider:
        server: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        user: "{{ lookup('env','F5_USERNAME') }}"
        password: "{{ lookup('env','F5_PASSWORD') }}"
        validate_certs: no
    delegate_to: localhost

  - name: Set list of nodes from survey
    set_fact:
      nodes: |
        {%- set nodes = nodes_list.split('\n') | select 
          | map("regex_replace", "^", "- {") 
          | map("regex_replace", "$", "}") 
          | join("\n") -%}
        {{ nodes | from_yaml}}
  - debug:
      msg: "{{ nodes }}"

  - name: Add pool members
    bigip_pool_member:
      pool: "{{ vs_name + '_pool'  }}"
      host: "{{ item.node_ip  }}"
      port: "{{ item.node_port }}"
      name: "{{ item.node_name }}"
      state: enabled
      provider:
        server: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        user: "{{ lookup('env','F5_USERNAME') }}"
        password: "{{ lookup('env','F5_PASSWORD') }}"
        validate_certs: no
    delegate_to: localhost
    loop: "{{ nodes }}"

  - name: Add virtual server without SNAT
    bigip_virtual_server:
      state: present
      partition: Common
      name: "{{ 'vs_' + vs_name }}"
      destination: "{{ vs_ip }}"
      port: "{{ vs_port | string }}"
      pool: "{{ vs_name + '_pool'  }}"
      ip_protocol: tcp
      snat: "{{ vs_snat }}"
      default_persistence_profile: "{{ persistence_profile_name.split('\n')[0] }}"
      profiles:
        - http
      enabled_vlans:
        - all
      provider:
        server: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        user: "{{ lookup('env','F5_USERNAME') }}"
        password: "{{ lookup('env','F5_PASSWORD') }}"
        validate_certs: no
    delegate_to: localhost