---
#Playbook to modify Local Admin Account on IOS devices
- name: F5 Virtual Server Configuration
  hosts: all
  connection: local
  gather_facts: false
  tasks:

  - name: Set list of nodes
    set_fact:
      nodes: >-
        {{ nodes_list.split("\n") | select | 
          map("regex_replace", "^", "- {") | 
          map("regex_replace", "$", "}") | 
          join("\n") | from_yaml }}

  - debug:
      msg: "{{  nodes_list  }}"

  - name: Add node
    bigip_node:
      host: 10.0.1.20
      name: site2
      state: disabled
      provider:
        server: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        user: "{{ lookup('env','F5_USERNAME') }}"
        password: "{{ lookup('env','F5_PASSWORD') }}"
        validate_certs: no
    delegate_to: localhost