---
#Playbook to modify Local Admin Account on IOS devices
- name: Change Admin Local Account on IOS Devices
  hosts: all
  gather_facts: false

  tasks:

  - name: debug
    debug:
      msg: "{{ lookup('env','NETBOX_TOKEN') }}"