---
#Playbook to modify Local Admin Account on IOS devices
- name: Change Admin Local Account on IOS Devices
  hosts: all
  connection: local
  gather_facts: false

  tasks:

  - name: Add node
    bigip_node:
      host: 10.0.1.10
      name: 10.0.1.10
      provider:
        server: "{{ inventory_hostname }}"
        user: "{{ lookup('env','F5_PASSWORD') }}"
        password: "{{ lookup('env','F5_USERNAME') }}"
    delegate_to: localhost