---
#Playbook to modify Local Admin Account on IOS devices
- name: Change Admin Local Account on IOS Devices
  hosts: all
  connection: local
  gather_facts: false

  tasks:

  - debug:
        msg: "{{   }}"

  - name: Add node
    bigip_node:
      host: 10.0.1.10
      name: 10.0.1.10
      provider:
        server: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        user: "{{ lookup('env','F5_USERNAME') }}"
        password: "{{ lookup('env','F5_PASSWORD') }}"
        validate_certs: no
    delegate_to: localhost