---
#Playbook to modify Local Admin Account on IOS devices
- name: F5 Virtual Server Configuration
  hosts: all
  connection: local
  gather_facts: false
  tasks:


  - name: Create HTTP Monitor
    bigip_monitor_http:
      state: present
      name: my_http_monitor_EVENG
      send: "{{ http_monitor_send  }}"
      receive: "{{ http_monitor_receive }}"
      provider:
        server: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        user: "{{ lookup('env','F5_USERNAME') }}"
        password: "{{ lookup('env','F5_PASSWORD') }}"
        validate_certs: no
    delegate_to: localhost
    when: http_monitor_select == 'ENABLED'

  - name: Set list of nodes from survey
    set_fact:
      nodes: |
        {%- set nodes = nodes_list.split('\n') | select 
          | map("regex_replace", "^", "- {") 
          | map("regex_replace", "$", "}") 
          | join("\n") -%}

        {{ nodes | from_yaml}}

  - name: Add F5 nodes 
    bigip_node:
      host: "{{ item.node_ip  }}"
      name: "{{ item.node_name }}"
      state: disabled
      provider:
        server: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        user: "{{ lookup('env','F5_USERNAME') }}"
        password: "{{ lookup('env','F5_PASSWORD') }}"
        validate_certs: no
    delegate_to: localhost
    loop: "{{ nodes }}"